namespace Scoria;

public enum Key
{
    // Control characters
    Tab = 9,
    Enter = 13,
    Escape = 27,
    Space = 32,
    Backspace = 127,

    // Digits
    D0 = '0',
    D1 = '1',
    D2 = '2',
    D3 = '3',
    D4 = '4',
    D5 = '5',
    D6 = '6',
    D7 = '7',
    D8 = '8',
    D9 = '9',

    // Uppercase letters
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    V = 'V',
    W = 'W',
    X = 'X',
    Y = 'Y',
    Z = 'Z',

    // Symbols
    Exclaim = '!',
    DoubleQuote = '"',
    Hash = '#',
    Dollar = '$',
    Percent = '%',
    Amp = '&',
    Quote = '\'',
    LParen = '(',
    RParen = ')',
    Star = '*',
    Plus = '+',
    Comma = ',',
    Minus = '-',
    Period = '.',
    Slash = '/',
    Colon = ':',
    Semicolon = ';',
    Lt = '<',
    Equal = '=',
    Gt = '>',
    Question = '?',
    At = '@',
    LBracket = '[',
    Backslash = '\\',
    RBracket = ']',
    Caret = '^',
    Underscore = '_',
    Backtick = '`',
    LBrace = '{',
    Pipe = '|',
    RBrace = '}',
    Tilde = '~',

    // Special / function keys (values intentionally above Unicode range)
    Up = 0x10000,
    Down,
    Left,
    Right,
    PageUp,
    PageDown,
    Home,
    End,
    Insert,
    Delete,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
}